# docker-compose.production.yml
version: '3'

volumes:
  kitty_pg_data:
  static:
  media:

services:
  kitty_db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - kitty_pg_data:/var/lib/postgresql/data
  kittygram_backend:
    image: testuseryccamp/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
  kittygram_frontend:
    image: testuseryccamp/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  kittygram_gateway:
    image: testuseryccamp/kittygram_gateway
    volumes:
      - static:/staticfiles/
      - media:/app/media
    ports:
      - 9000:80
