# Файл docker-compose.yml
version: '3'

volumes:
  kitty_pg_data:
  static:
  media:

services:
  kitty_db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - kitty_pg_data:/var/lib/postgresql/data
  kittygram_backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
  kittygram_frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  kittygram_gateway:
    build: ./nginx/
    volumes:
      - static:/staticfiles/
      - media:/app/media
    ports:
      - 9000:80 
