# Файл docker-compose.yml
version: '3'

volumes:
  kitty_pg_data:
  static:

services:
  kitty_db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - kitty_pg_data:/var/lib/postgresql/data
  kittygram_backend:
    image: testuseryccamp/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
  kittygram_frontend:
    image: testuseryccamp/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    

# Добавляем новый контейнер: gateway.
  kittygram_nginx:
    image: testuseryccamp/kittygram_nginx
    # А тут подключаем volume со статикой к gateway
    volumes:
      - static:/staticfiles/
    ports:
      - 9000:80
