# Файл docker-compose.yml
version: '3'

volumes:
  kitty_pg_data:
  static:

services:
  kitty_db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - kitty_pg_data:/var/lib/postgresql/data
  kitty_backend:
    image: testuseryccamp/kitty_backend
    env_file: .env
    volumes:
      - static:/backend_static
  kitty_frontend:
    image: testuseryccamp/kitty_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    

# Добавляем новый контейнер: gateway.
  kitty_gateway:
    image: testuseryccamp/kitty_gateway
    # А тут подключаем volume со статикой к gateway
    volumes:
      - static:/staticfiles/
    ports:
      - 8080:80 
